In [15]:
import pandas as pd
import numpy as np

df = pd.read_csv("employee_turnover.csv")

df

,Job_Satisfaction,Performance_Rating,Years_At_Company,Work_Life_Balance,Distance_From_Home,Monthly_Income,Education_Level,Age,Num_Companies_Worked,Employee_Role,Annual_Bonus,Training_Hours,Department,Annual_Bonus_Squared,Annual_Bonus_Training_Hours_Interaction,Employee_Turnover
0,0.562326,0.141129,0.123989,0.347583,0.330353,0.328853,0.600933,0.315990,0.768736,0.090671,0.324786,0.669193,0.602932,0.105486,0.217344,0
1,0.017041,0.559047,0.511203,0.793908,0.423550,0.553450,0.742009,0.897146,0.380035,0.601633,0.694611,0.043271,0.800761,0.482484,0.030056,0
2,0.774699,0.604371,0.798174,0.260500,0.804034,0.131800,0.775178,0.830947,0.218726,0.972936,0.153476,0.701336,0.705275,0.023555,0.107638,1
3,0.628174,0.385249,0.230104,0.516809,0.272248,0.589249,0.482409,0.090507,0.402746,0.132842,0.305973,0.549688,0.600531,0.093620,0.168190,0
4,0.799183,0.199967,0.839029,0.247927,0.341934,0.076818,0.055356,0.680860,0.923341,0.493017,0.844094,0.793751,0.664679,0.712494,0.670000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1345,0.914733,0.965914,0.147215,0.686677,0.251346,0.572003,0.089679,0.127247,0.125553,0.346950,0.450783,0.754675,0.905320,0.203205,0.340194,1
1346,0.396906,0.182952,0.877941,0.824077,0.774960,0.057290,0.556719,0.235014,0.119685,0.781613,0.211581,0.500812,0.526096,0.044767,0.105962,1
1347,0.099171,0.363498,0.849120,0.462270,0.763922,0.585370,0.975760,0.557090,0.782690,0.384706,0.449095,0.270280,0.253656,0.201686,0.121381,1
1348,0.048193,0.453892,0.640611,0.335230,0.952724,0.638797,0.993664,0.801292,0.510281,0.164325,0.649934,0.151225,0.405705,0.422414,0.098286,1
1349,0.496702,0.523527,0.779612,0.320897,0.048957,0.637470,0.908619,0.587263,0.236790,0.265646,0.358821,0.870967,0.828226,0.128753,0.312521,0

In [16]:
df.shape

(1350, 16)

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1350 entries, 0 to 1349
Data columns (total 16 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Job_Satisfaction                         1350 non-null   float64
 1   Performance_Rating                       1350 non-null   float64
 2   Years_At_Company                         1350 non-null   float64
 3   Work_Life_Balance                        1350 non-null   float64
 4   Distance_From_Home                       1350 non-null   float64
 5   Monthly_Income                           1350 non-null   float64
 6   Education_Level                          1350 non-null   float64
 7   Age                                      1350 non-null   float64
 8   Num_Companies_Worked                     1350 non-null   float64
 9   Employee_Role                            1350 non-null   float64
 10  Annual_Bonus                             1350 non-null   float64
 11  Training_Hours                           1350 non-null   float64
 12  Department                               1350 non-null   float64
 13  Annual_Bonus_Squared                     1350 non-null   float64
 14  Annual_Bonus_Training_Hours_Interaction  1350 non-null   float64
 15  Employee_Turnover                        1350 non-null   int64
dtypes: float64(15), int64(1)
memory usage: 168.9 KB

In [18]:
df.describe()

,Job_Satisfaction,Performance_Rating,Years_At_Company,Work_Life_Balance,Distance_From_Home,Monthly_Income,Education_Level,Age,Num_Companies_Worked,Employee_Role,Annual_Bonus,Training_Hours,Department,Annual_Bonus_Squared,Annual_Bonus_Training_Hours_Interaction,Employee_Turnover
count,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1.350000e+03,1350.000000,1350.000000
mean,0.506386,0.487061,0.484761,0.499442,0.494884,0.509909,0.504329,0.500164,0.516149,0.506091,0.493360,0.486843,0.485767,3.291479e-01,0.240653,0.497778
std,0.291505,0.283808,0.282758,0.293013,0.289248,0.290110,0.295693,0.294835,0.295072,0.284901,0.292929,0.288342,0.285077,2.986314e-01,0.222281,0.500180
min,0.001738,0.000546,0.001545,0.000166,0.001319,0.005015,0.000424,0.000231,0.000150,0.000903,0.000491,0.001293,0.001595,2.410000e-07,0.000247,0.000000
25%,0.263051,0.238538,0.249651,0.246399,0.244162,0.263235,0.249894,0.239224,0.247978,0.269517,0.247274,0.233357,0.244944,6.114448e-02,0.058694,0.000000
50%,0.525340,0.468457,0.485414,0.495572,0.501617,0.532388,0.509448,0.499964,0.531408,0.504640,0.498490,0.475214,0.468982,2.484923e-01,0.165438,0.000000
75%,0.750987,0.724088,0.721622,0.753108,0.743938,0.761090,0.755113,0.767168,0.775888,0.761640,0.740231,0.747609,0.725870,5.479425e-01,0.367042,1.000000
max,0.998692,0.999957,0.999722,0.999931,0.997813,0.999143,0.999794,0.998365,0.999962,0.999964,0.998211,0.998330,0.999386,9.964245e-01,0.930338,1.000000

In [19]:
df.isnull().sum()

Job_Satisfaction                           0
Performance_Rating                         0
Years_At_Company                           0
Work_Life_Balance                          0
Distance_From_Home                         0
Monthly_Income                             0
Education_Level                            0
Age                                        0
Num_Companies_Worked                       0
Employee_Role                              0
Annual_Bonus                               0
Training_Hours                             0
Department                                 0
Annual_Bonus_Squared                       0
Annual_Bonus_Training_Hours_Interaction    0
Employee_Turnover                          0
dtype: int64

In [20]:
df.duplicated().sum()

np.int64(450)

In [22]:
x = df.drop("Employee_Turnover", axis=1)
y = df["Employee_Turnover"]

In [23]:
#Train Test Split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [26]:
# Baseline Logistic Regression
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=500)
lr.fit(x_train, y_train)

# L1 Regularizaiton (Lasso)
lasso = LogisticRegression(penalty='l1', solver='liblinear', C=0.05)
lasso.fit(x_train, y_train)

# L2 Regularizatio (Ridge)

ridge = LogisticRegression(penalty='l2', C=1, max_iter=500)
ridge.fit(x_train, y_train)

LogisticRegression(C=1, max_iter=500)

In [27]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix , classification_report

model = {"Baseline": lr, "Lasso": lasso, "Ridge": ridge}

for name,model in model.items():
    y_pred = model.predict(x_test)
    print(f"\n{name}:")
    print("Accuracy:", accuracy_score(y_test, y_pred)*100,"%")
    print("Precision:", precision_score(y_test, y_pred)*100,"%")
    print("Recall:", recall_score(y_test, y_pred)*100,"%")
    print("F1:", f1_score(y_test, y_pred)*100,"%")
    print("Confusion Matrix: ", confusion_matrix(y_test, y_pred)*100,"%")
    print(classification_report(y_test, y_pred))

Baseline:
Accuracy: 85.92592592592592 %
Precision: 87.17948717948718 %
Recall: 81.6 %
F1: 84.29752066115702 %
Confusion Matrix:  [[13000  1500]
 [ 2300 10200]] %
              precision    recall  f1-score   support

           0       0.85      0.90      0.87       145
           1       0.87      0.82      0.84       125

    accuracy                           0.86       270
   macro avg       0.86      0.86      0.86       270
weighted avg       0.86      0.86      0.86       270


Lasso:
Accuracy: 81.48148148148148 %
Precision: 76.97841726618705 %
Recall: 85.6 %
F1: 81.06060606060606 %
Confusion Matrix:  [[11300  3200]
 [ 1800 10700]] %
              precision    recall  f1-score   support

           0       0.86      0.78      0.82       145
           1       0.77      0.86      0.81       125

    accuracy                           0.81       270
   macro avg       0.82      0.82      0.81       270
weighted avg       0.82      0.81      0.82       270


Ridge:
Accuracy: 85.92592592592592 %
Precision: 87.17948717948718 %
Recall: 81.6 %
F1: 84.29752066115702 %
Confusion Matrix:  [[13000  1500]
 [ 2300 10200]] %
              precision    recall  f1-score   support

           0       0.85      0.90      0.87       145
           1       0.87      0.82      0.84       125

    accuracy                           0.86       270
   macro avg       0.86      0.86      0.86       270
weighted avg       0.86      0.86      0.86       270